# This is a basic workflow to help you get started with Actions

name: Wygeneruj

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
#  push:
#    branches: [ "main" ]
#  pull_request:
#    branches: [ "main" ]
  repository_dispatch:
    types: [ "dodaja4" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  Generate_S:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x' # Choose the appropriate Python version
      - name: Install dependencies
        run: pip install Pillow # Install Pillow library

      - name: Download File
        run: |
         curl -L https://limsezam.ovh/generated/laptop.png -o gen/add.png
         

      - name: Import to page
        run: python gen/page_import.py

      - name: Upload
        uses: wlixcc/SFTP-Deploy-Action@v1.2.4
        with:
            username: ${{ secrets.SFTP_USERNAME }}
            server: ${{ secrets.SFTP_SERVER }}
            port: 22
            local_path: './a4_page.png'
            remote_path: '/public/generated_pages/laptop_list.png'
            sftp_only: true
            password: ${{ secrets.SFTP_PASSWORD }}



            
  Generate_M:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x' # Choose the appropriate Python version
      - name: Install dependencies
        run: pip install Pillow # Install Pillow library

      - name: Download File
        run: |
         curl -L https://limsezam.ovh/generated/tv.png -o gen/add.png
         

      - name: Import to page
        run: python gen/page_import.py

      - name: Upload
        uses: wlixcc/SFTP-Deploy-Action@v1.2.4
        with:
            username: ${{ secrets.SFTP_USERNAME }}
            server: ${{ secrets.SFTP_SERVER }}
            port: 22
            local_path: './a4_page.png'
            remote_path: '/public/generated_pages/tv_list.png'
            sftp_only: true
            password: ${{ secrets.SFTP_PASSWORD }}
