name: Wygeneruj

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  repository_dispatch:
    types: [ "generuj" ]
  workflow_dispatch:

jobs:
  prepare_files:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install Pillow

      - name: Download Files
        run: |
          curl -L https://limsezam.ovh/input/input_0.txt -o gen/title.txt && \
          curl -L https://limsezam.ovh/input/input_1.txt -o gen/desc.txt && \
          curl -L https://limsezam.ovh/input/input_2.txt -o gen/sub1.txt && \
          curl -L https://limsezam.ovh/input/input_3.txt -o gen/text1.txt && \
          curl -L https://limsezam.ovh/input/input_4.txt -o gen/sub2.txt && \
          curl -L https://limsezam.ovh/input/input_5.txt -o gen/text2.txt && \
          curl -L https://limsezam.ovh/input/input_6.txt -o gen/sub3.txt && \
          curl -L https://limsezam.ovh/input/input_7.txt -o gen/text3.txt && \
          curl -L https://limsezam.ovh/input/input_8.txt -o gen/text4.txt && \
          curl -L https://limsezam.ovh/input/price.txt -o gen/price.txt && \
          curl -L https://limsezam.ovh/input/promotion.txt -o gen/promotion.txt && \
          curl -L https://limsezam.ovh/input/selected_option.txt -o gen/selected_option.txt && \
          curl -L https://limsezam.ovh/input/extra5.txt -o gen/extra5.txt && \
          curl -L https://limsezam.ovh/input/extra5_desc.txt -o gen/extra5_desc.txt

  generate_images:
    needs: prepare_files
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Generate Images - Small (Laptop)
        run: python gen/laptop.py
        continue-on-error: true

      - name: Generate Images - Med (TV)
        run: python gen/tv.py
        continue-on-error: true

      - name: Generate Images - Big (A4)
        run: python gen/a4.py
        continue-on-error: true

  upload_images:
    needs: generate_images
    runs-on: ubuntu-latest
    steps:
      - name: Upload Images
        uses: wlixcc/SFTP-Deploy-Action@v1.2.4
        with:
          username: ${{ secrets.SFTP_USERNAME }}
          server: ${{ secrets.SFTP_SERVER }}
          port: 22
          sftp_only: true
          password: ${{ secrets.SFTP_PASSWORD }}
          local_path: |
            laptop.png
            tv.png
            a4.png
          remote_path: |
            /public/generated/laptop.png
            /public/generated/tv.png
            /public/generated/a4.png
