# This is a basic workflow to help you get started with Actions

name: Wygeneruj

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Setup Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x' # Choose the appropriate Python version

      - name: Install dependencies
        run: pip install Pillow # Install Pillow library

      - name: Generate Images - Small (Laptop)
        run: python gen/laptop.py # Run your Python script


      - name: Upload Small
        uses: actions/upload-artifact@v4
        with:
          name: Opisowka_Laptop
          path: laptop.png


      - name: Upload Small
        uses: wlixcc/SFTP-Deploy-Action@v1.2.4
        with:
            username: ${{ secrets.SFTP_USERNAME }}
            server: ${{ secrets.SFTP_SERVER }}
            port: 22
            local_path: './laptop.png'
            remote_path: '/public/generated/laptop.png'
            sftp_only: true
            password: ${{ secrets.SFTP_PASSWORD }}












      - name: Generate Images - Med (TV)
        run: python gen/tv.py # Run your Python script

      - name: Generate Images - Big (A4)
        run: python gen/a4.py # Run your Python script
